package com.selloLegitimo.GestionPreElectoral.modelo;

public enum TipoAccionAuditoria {
	CREATE,
	UPDATE,
	DELETE,
	SIGN,
	EXPORT,
	TRANSITION,
	APPROVE,
	REJECT,
	IMPORT,
	FREEZE,
	LOGIN,
	LOGIN_FAILED,
	MFA_SETUP,
	MFA_VERIFY_SUCCESS,
	MFA_VERIFY_FAIL,
	CEREMONY_INITIATE,
	SHARD_SUBMITTED,
	CEREMONY_COMPLETED,
	CEREMONY_ABORT
}