package com.selloLegitimo.GestionPreElectoral.modelo;

public enum TipoEventoAuditoria {
	CANDIDATURA_POSTULADA,
	CANDIDATURA_ACTUALIZADA,
	CANDIDATURA_ESTADO_CAMBIADO,
	CANDIDATURA_REEMPLAZADA,
	CANDIDATURA_APROBADA,
	CANDIDATURA_RECHAZADA,
	CANDIDATURA_PUBLICADA,
	TARJETON_GENERADO
}
